routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', ['as' => 'index', 'uses' => 'HomeController@index']);
Route::get('/search', ['as' => 'post.search', 'uses' => 'HomeController@search']);
Route::get('/post/{slug}', ['as' => 'post.slug', 'uses' => 'HomeController@show']);
Route::get('/category/{id}/posts', ['as' => 'category.posts', 'uses' => 'HomeController@categoryPost']);
Route::post('/send-email', ['as' => 'email.send', 'uses' => 'HomeController@sendMail']);

Auth::routes();
Route::group(['namespace' => 'Admin'], function () {
    Route::post('media/upload', 'MediaController@upload');
});
Route::group(
    [
        'prefix' => 'admin',
        'middleware' => ['auth', 'isManager'] ,
        'namespace' => 'Admin'
    ], function () {
        Route::get(
            '/',
            [
                'as' => 'admin.dashboard',
                'uses' => 'DashboardController@index'
            ]
        );

        Route::get(
            'users/as-json',
            [
                'uses' => 'UserController@asJson',
                'as' => 'admin.users.as.json'
            ]
        );
        Route::get(
            'users/profile-setting',
            [
                'uses' => 'UserController@getProfile',
                'as' => 'users.profile'
            ]
        );
        Route::put(
            'users/profile-setting',
            [
                'uses' => 'UserController@updateProfile',
                'as' => 'users.profile'
            ]
        );
        Route::get(
            'posts/as-json', 
            [
                'uses' => 'PostController@asJson',
                'as' => 'admin.posts.as.json'
            ]
        );
        Route::get(
            'categories/as-json', 
            [
                'uses' => 'CategoryController@asJson',
                'as' => 'admin.categories.as.json'
            ]
        );
        Route::resources(
            [
                'users' => 'UserController',
                'categories' => 'CategoryController',
                'posts' => 'PostController',
            ]
        );
    }
);

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;

class Post extends Model
{
    use SoftDeletes;
    protected $guarded = ['id'];

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id', 'id');
    }

    public function category()
    {
        return $this->belongsTo(Category::class, 'category_id', 'id')->withTrashed();
    }
    public function getImageUrl()
    {
        return asset("storage/{$this->image}");
    }

    public function getLimitContent($limit = 100, $end = '...')
    {
        return Str::limit($this->content, $limit, $end);
    }

    public function getPublished()
    {
        $time = strtotime($this->published_at);
        return $this->published_at ? date('d/m/y', $time) : '?';
    }
    public function getExpired()
    {
        $time = strtotime($this->expired_at);
        return $this->expired_at ? date('d/m/y', $time) : '?';
    }

    public function getDay()
    {
        return $this->created_at->day;
    }

    public function getYear()
    {
        return $this->created_at->year;
    }

    public function getMonth()
    {
        return $this->created_at->month;
    }
}

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Services\CategoryService;
use Illuminate\Http\Request;
use App\Http\Requests\Admin\PostRequest;

use App\Services\PostService;
use App\Services\UserService;

class PostController extends Controller
{
    public function __construct(PostService $postService, UserService $userService, CategoryService $categoriService)
    {
        $this->service = $postService;
        $this->userService = $userService;
        $this->categoriService = $categoriService;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $allUser = $this->userService->getAllUserSelectBox();
        return view('admin.posts.index')->with(compact('allUser'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categoriesSelect = $this->categoriService->getAllCategorySelectBox();
        return view('admin.posts.create')->with(compact('categoriesSelect'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PostRequest $request)
    {
        return $this->service->savePost($request);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = $this->service->find($id);
        $categoriesSelect = $this->categoriService->getAllCategorySelectBox();
        return view('admin.posts.edit')->with(compact('post', 'categoriesSelect'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(PostRequest $request, $id)
    {
        return $this->service->findAndUpdatePost($id, $request);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->service->findAndDelete($id);

        return response()->json(['code' => 200, 'msg' => 'Đã xoá']);
    }
    /**
     * Undocumented function
     *
     * @param Request $request
     * @return json
     */
    public function asJson(Request $request)
    {
        return $this->service->getAsJson($request->only('user_id', 'type'));
    }
}

resources/views/admin/posts/create.blade.php
@extends('admin.layouts.layouts')
@section('css')
    <link href="{{asset('admin/plugins/dropzone/dropzone.css')}}" rel="stylesheet">
    <!-- Bootstrap Material Datetime Picker Css -->
    <link href="/admin/plugins/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css" rel="stylesheet" />

    <!-- Bootstrap DatePicker Css -->
    <link href="/admin/plugins/bootstrap-datepicker/css/bootstrap-datepicker.css" rel="stylesheet" />

    <style>
        .dz-image {
          width: 100% !important;
          height: 100% !important;
        }
        .dz-preview {
          width: 90% !important;
          height: 90% !important
        }
    </style>
@stop
@section('content')
<div class="container-fluid">
  <div class="block-header">
    <h2>
      Quản lý bài viết
    </h2>
  </div>
  <!-- Basic Examples -->
  <div class="row clearfix">

    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="header">
          <h2>
            Tạo mới bài viết
          </h2>
        </div>
        <div class="body">
          @include('admin.includes.errors')
          @include('admin.includes.success')

          {!! Form::open(['route' => 'posts.store', 'method' => 'POST', 'id' => 'frmCreatePost', 'class' => 'dropzone', 'files' => true]) !!}
          <div class="row clearfix">

            <div class="col-sm-6">
              <div class="form-group form-float">
                <div class="form-line">
                  {!! Form::select('category_id', $categoriesSelect, '', ['class' => 'form-control show-tick', 'id' => 'categoryId', 'required' => true]) !!}
                  <label class="form-label">Mục</label>
                </div>
              </div>
            </div>
            <div class="col-sm-6">
              <div class="form-group form-float">
                <div class="form-line">
                  {!! Form::text('title', '', [
                  'class' => 'form-control',
                  'required' => true,
                  'minlength' => 10,
                  'maxlength' => 255
                  ])!!}
                  <label class="form-label">Tiêu đề</label>
                </div>
              </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group form-float">
                  <div class="form-line">
                    {!! Form::select('type', config('post.post_type'), '', ['class' => 'form-control show-tick', 'id' => 'postType', 'required' => true]) !!}
                    <label class="form-label">Loại bài viết</label>
                  </div>
                </div>
              </div>
            <div class="col-sm-6">
              <div class="form-group form-float">
                <div class="form-line">
                  {!! Form::text('source', '', ['class' => 'form-control',
                  'minlength' => 5,
                  'maxlength' => 100
                  ]) !!}
                  <label class="form-label">Nguồn</label>
                </div>
              </div>
            </div>

            <div class="col-sm-6">
              <div class="form-group form-float">
                <div class="form-line">
                  {!! Form::text('published_at', '', ['class' => 'form-control datepicker']) !!}
                  <label class="form-label">Ngày bắt đầu</label>
                </div>
              </div>
            </div>

            <div class="col-sm-6">
              <div class="form-group form-float">
                <div class="form-line">
                  {!! Form::text('expired_at', '', ['class' => 'form-control datepicker']) !!}
                  <label class="form-label">Ngày kết thúc</label>
                </div>
              </div>
            </div>

            <div class="col-sm-12">
              <div class="form-group form-float">
                <span>Miêu tả ngắn: </span>
                <div class="form-line">
                  {!! Form::textarea('description', null, ['id' => 'post_desciption', 'required' => true]) !!}
                </div>
              </div>
            </div>

            <div class="col-sm-12">
              <div class="form-group form-float">
                <span>Nội dung: </span>
                <div class="form-line">
                  {!! Form::textarea('content', null, ['id' => 'tinymce', 'required' => true]) !!}
                </div>
              </div>
            </div>

            
            <div class="col-sm-12 ">
                <label class="form-label">Ảnh</label>
                <div class="dz-message">
                    <div class="drag-icon-cph">
                        <i class="material-icons">touch_app</i>
                    </div>
                    <h3>Kéo thả hoặc click để upload ảnh</h3>
                    <em>(Chọn ảnh cho bài viết)</em>
                </div>
                <div class="fallback">
                    <input name="image" type="file" required/>
                </div>
            </div>

            <div class="col-sm-12">
              <button type="button" class="btn btn-primary btn-lg m-l-15 waves-effect" id='createBtn'>Cập nhật</button>
            </div>
          </div>
          {!! Form::close() !!}
        </div>
      </div>
    </div>
  </div>
  <!-- #END# Basic Examples -->

</div>
@stop

@section('js')
    <script src="/admin/plugins/jquery-validation/jquery.validate.js"></script>
    <script src="/admin/plugins/dropzone/dropzone.js"></script>
    <script src="/admin/plugins/tinymce/tinymce.min.js"></script>
    <script src="/admin/js/pages/forms/editors.js"></script>
    <!-- Moment Plugin Js -->
    <script src="/admin/plugins/momentjs/moment.js"></script>

    <!-- Bootstrap Material Datetime Picker Plugin Js -->
    <script src="/admin/plugins/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js"></script>

    <!-- Bootstrap Datepicker Plugin Js -->
    <script src="/admin/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
    <script>
        var createPost = $('#frmCreatePost');

        $(function() {
          $('.datepicker').bootstrapMaterialDatePicker({
              format: 'DD-MM-YYYY',
              clearButton: true,
              weekStart: 1,
              time: false
          });

            createPost.validate({
                highlight: function (input) {
                    $(input).parents('.form-line').addClass('error');
                },
                unhighlight: function (input) {
                    $(input).parents('.form-line').removeClass('error');
                },
                errorPlacement: function (error, element) {
                    $(element).parents('.form-group').append(error);
                }
            });
        
        
            Dropzone.options.frmCreatePost = {
                paramName: "image",
                maxFilesize: 20,
                maxFiles: 1,
                uploadMultiple: false,
                addRemoveLinks: true,
                acceptedFiles: '.jpg, .jpeg, .gif, .png',
                dictRemoveFile: 'Xoá file',
                autoProcessQueue: false,
                init: function () {
                    var submitButton = document.querySelector("#createBtn");
                    var myDropzone = this;
                    submitButton.addEventListener("click", function (e) {
                        e.preventDefault();
                        e.stopPropagation();
                        if(createPost.valid()){
                            myDropzone.processQueue();
                        }
                    });
                    this.on("thumbnail", function(file, dataUrl) {
                        $('.dz-image').last().find('img').attr({width: '100%', height: '100%'});
                    }),
                    this.on('sending', function (file, xhr, formData) {
                        var data = $('form').serializeArray();
                        tinymce.triggerSave();
                        $.each(data, function (key, el) {
                            formData.append(el.name, el.value);
                        });
                    });
                    this.on('success', function (data, response) {
                        $('.dz-image').css({"width":"100%", "height":"auto"});
                        toastr.clear();
                        if (response.code == 200) {
                            toastr.success(response.message, 'Thông Báo');
                            setTimeout(function(){
                                window.location.href = response.data.url;
                            }, 1000);
                        } else {
                            toastr.error(response.message, 'Thông Báo');
                            setTimeout(function(){
                                window.location.reload();
                            }, 1000);
                        }
                    });
        
                    this.on('error', function (file, response) {
                        var errorsMsg = '<ul class="list-group error-msg">';
        
                        if(response.code === 500) {
                            errorsMsg += '<li style="border-bottom: 2px solid #fff" class="list-group-item list-group-item-danger">';
                            errorsMsg += 'Đã xảy ra lỗi trong thao tác, vui lòng thử lại';
                            errorsMsg += '</li>';
                        } else{
                            for (var i in response.errors) {
                                errorsMsg += '<li style="border-bottom: 2px solid #fff" class="list-group-item list-group-item-danger">';
                                errorsMsg += response.errors[i].shift();
                                errorsMsg += '</li>';
                            }
                        }
                        errorsMsg += '</ul>';
        
                        $('.body').find('.error-msg').remove();
                        $('.body').prepend(errorsMsg);
        
                    });
                    this.on('maxfilesexceeded', function(file) {
                        myDropzone.removeFile( file );
                    })
                }
            };
        
        });
            
    </script>
@stop

resources/views/admin/posts/edit.blade.php
@extends('admin.layouts.layouts')
@section('css')
    <link href="{{asset('admin/plugins/dropzone/dropzone.css')}}" rel="stylesheet">
    <!-- Bootstrap Material Datetime Picker Css -->
    <link href="/admin/plugins/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css" rel="stylesheet" />

    <!-- Bootstrap DatePicker Css -->
    <link href="/admin/plugins/bootstrap-datepicker/css/bootstrap-datepicker.css" rel="stylesheet" />

    <style>
        .dz-image {
          width: 100% !important;
          height: 100% !important;
        }
        .dz-preview {
          width: 90% !important;
          height: 90% !important
        }
    </style>
@stop
@section('content')
<div class="container-fluid">
  <div class="block-header">
    <h2>
      Quản lý bài viết
    </h2>
  </div>
  <!-- Basic Examples -->
  <div class="row clearfix">

    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="card">
        <div class="header">
          <h2>
            Sửa bài viết
          </h2>
        </div>
        <div class="body">
          @include('admin.includes.errors')
          @include('admin.includes.success')

          {!! Form::open(['route' => ['posts.update', $post->id], 'method' => 'PUT', 'id' => 'frmEditPost', 'class' => 'dropzone', 'files' => true]) !!}
          <div class="row clearfix">

            <div class="col-sm-6">
              <div class="form-group form-float">
                <div class="form-line">
                  {!! Form::select('category_id', $categoriesSelect, $post->category_id, ['class' => 'form-control show-tick', 'id' => 'categoryId', 'required' => true]) !!}
                  <label class="form-label">Mục</label>
                </div>
              </div>
            </div>
            <div class="col-sm-6">
              <div class="form-group form-float">
                <div class="form-line">
                  {!! Form::text('title', $post->title, [
                  'class' => 'form-control',
                  'required' => true,
                  'minlength' => 10,
                  'maxlength' => 255
                  ])!!}
                  <label class="form-label">Tiêu đề</label>
                </div>
              </div>
            </div>
            <div class="col-sm-6">
              <div class="form-group form-float">
                <div class="form-line">
                  {!! Form::text('source', $post->source, ['class' => 'form-control',
                  'minlength' => 5,
                  'maxlength' => 100
                  ]) !!}
                  <label class="form-label">Nguồn</label>
                </div>
              </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group form-float">
                    <div class="form-line">
                      <label class="form-label">Trạng thái: </label>
                        {!! Form::select('active', config('post.post_status'), $post->active, ['class' => 'form-control show-tick', 'id' => 'postType']) !!}
                      </div>
                </div>
            </div>
            <div class="col-sm-6">
              <div class="form-group form-float">
                <div class="form-line">
                  {!! Form::text('published_at', $post->published_at, ['class' => 'form-control datepicker']) !!}
                  <label class="form-label">Ngày bắt đầu</label>
                </div>
              </div>
            </div>

            <div class="col-sm-6">
              <div class="form-group form-float">
                <div class="form-line">
                  {!! Form::text('expired_at', $post->expired_at, ['class' => 'form-control datepicker']) !!}
                  <label class="form-label">Ngày kết thúc</label>
                </div>
              </div>
            </div>

            <div class="col-sm-12">
                <div class="form-group form-float">
                  <span>Miêu tả ngắn: </span>
                  <div class="form-line">
                    {!! Form::textarea('description', $post->description, ['id' => 'post_desciption', 'required' => true]) !!}
                  </div>
                </div>
              </div>

            <div class="col-sm-12">
              <div class="form-group form-float">
                  <span>Miêu tả ngắn: </span>
                <div class="form-line">
                  {!! Form::textarea('content', $post->content, ['id' => 'tinymce', 'required' => true]) !!}
                </div>
              </div>
            </div>

            
            <div class="col-sm-12 ">
                <label class="form-label">Ảnh</label>
                <div class="dz-message">
                    <div class="drag-icon-cph">
                        <i class="material-icons">touch_app</i>
                    </div>
                    <h3>Kéo thả hoặc click để upload ảnh</h3>
                    <em>(Chọn ảnh cho bài viết)</em>
                </div>
                <div class="fallback">
                    <input name="image" type="file" required/>
                </div>
            </div>

            <div class="col-sm-12">
              <button type="button" class="btn btn-primary btn-lg m-l-15 waves-effect" id='createBtn'>Cập nhật</button>
            </div>
          </div>
          {!! Form::close() !!}
        </div>
      </div>
    </div>
  </div>
  <!-- #END# Basic Examples -->

</div>
@stop

@section('js')
    <script src="/admin/plugins/jquery-validation/jquery.validate.js"></script>
    <script src="/admin/plugins/dropzone/dropzone.js"></script>
    <script src="/admin/plugins/tinymce/tinymce.min.js"></script>
    <script src="/admin/js/pages/forms/editors.js"></script>
    <!-- Moment Plugin Js -->
    <script src="/admin/plugins/momentjs/moment.js"></script>

    <!-- Bootstrap Material Datetime Picker Plugin Js -->
    <script src="/admin/plugins/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js"></script>

    <!-- Bootstrap Datepicker Plugin Js -->
    <script src="/admin/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
    <script>
        var editPost = $('#frmEditPost');
        var images = [];
        var name = "{{ $post->getImageUrl() }}";
        var postId = "{{ $post->id }}";
        images.push({
            name: name, size: 321, id: postId
        });

        $(function() {
          $('.datepicker').bootstrapMaterialDatePicker({
              format: 'DD-MM-YYYY',
              clearButton: true,
              weekStart: 1,
              time: false
          });

            editPost.validate({
                highlight: function (input) {
                    $(input).parents('.form-line').addClass('error');
                },
                unhighlight: function (input) {
                    $(input).parents('.form-line').removeClass('error');
                },
                errorPlacement: function (error, element) {
                    $(element).parents('.form-group').append(error);
                }
            });
        
        
            Dropzone.options.frmEditPost = {
                paramName: "image",
                maxFilesize: 20,
                maxFiles: 1,
                uploadMultiple: false,
                addRemoveLinks: true,
                acceptedFiles: '.jpg, .jpeg, .gif, .png',
                dictRemoveFile: 'Xoá file',
                autoProcessQueue: false,
                init: function () {
                    var submitButton = document.querySelector("#createBtn");
                    var myDropzone = this;
                    images.forEach(function(image) {
                        myDropzone.options.addedfile.call(myDropzone, image);
                        myDropzone.options.thumbnail.call(myDropzone, image, image.name);
        
                    });
                    submitButton.addEventListener("click", function (e) {
                        e.preventDefault();
                        e.stopPropagation();
                        if (myDropzone.getQueuedFiles().length > 0) {                        
                                myDropzone.processQueue();  
                            } else {                       
                                editPost.submit();
                            }    
                    });
                    this.on("thumbnail", function(file, dataUrl) {
                        $('.dz-image').last().find('img').attr({width: '100%', height: '100%'});
                    }),
                    this.on('sending', function (file, xhr, formData) {
                        var data = $('form').serializeArray();
                        tinymce.triggerSave();
                        $.each(data, function (key, el) {
                            formData.append(el.name, el.value);
                        });
                    });
                    this.on('success', function (data, response) {
                        $('.dz-image').css({"width":"100%", "height":"auto"});
                        toastr.clear();
                        if (response.code == 200) {
                            toastr.success(response.message, 'Thông Báo');
                            setTimeout(function(){
                                window.location.href = response.data.url;
                            }, 1000);
                        } else {
                            toastr.error(response.message, 'Thông Báo');
                            setTimeout(function(){
                                window.location.reload();
                            }, 1000);
                        }
                    });
        
                    this.on('error', function (file, response) {
                        var errorsMsg = '<ul class="list-group error-msg">';
        
                        if(response.code === 500) {
                            errorsMsg += '<li style="border-bottom: 2px solid #fff" class="list-group-item list-group-item-danger">';
                            errorsMsg += 'Đã xảy ra lỗi trong thao tác, vui lòng thử lại';
                            errorsMsg += '</li>';
                        } else{
                            for (var i in response.errors) {
                                errorsMsg += '<li style="border-bottom: 2px solid #fff" class="list-group-item list-group-item-danger">';
                                errorsMsg += response.errors[i].shift();
                                errorsMsg += '</li>';
                            }
                        }
                        errorsMsg += '</ul>';
        
                        $('.body').find('.error-msg').remove();
                        $('.body').prepend(errorsMsg);
        
                    });
                    this.on('maxfilesexceeded', function(file) {
                        myDropzone.removeFile( file );
                    })
                }
            };
        
        });
            
    </script>
@stop

resources/views/admin/posts/index.blade.php
@extends('admin.layouts.table')


@section('table')
    <div class="container-fluid">
        <div class="block-header">
            <h2>
                Quản lý bài viết
            </h2>
        </div>
        <!-- Basic Examples -->
        <div class="row clearfix">

            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">

                <div class="card">
                    <div class="header">
                        <h2>
                            Danh sách bài posts
                        </h2>
                    </div>
                    <div class="body">
                        <div class="row clearfix">
                            <div class="col-sm-3">
                                <h5 class="card-inside-title">Tác giả:</h5>
                                <div class="form-group form-float">
                                    <div class="form-line">
                                        {!! Form::select('user_id', $allUser, '', ['class' => 'form-control show-tick', 'id' => 'userId', 'data-live-search' => 'true']) !!}
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-3">
                                <h5 class="card-inside-title">Loại bài viết:</h5>
                                <div class="form-group form-float">
                                    <div class="form-line">
                                        {!! Form::select('type', array_replace(['' => 'Tất cả'], config('post.post_type')), '', ['class' => 'form-control show-tick', 'id' => 'postType']) !!}
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-3">
                                <h5 class="card-inside-title">Trạng thái:</h5>
                                <div class="form-group form-float">
                                    <div class="form-line">
                                        {!! Form::select('active', array_replace(['' => 'Tất cả'], config('post.post_status')), '', ['class' => 'form-control show-tick', 'id' => 'postType']) !!}
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-5 text-right">
                                <a href="{{ route('posts.create') }}" class="btn">Tạo mới bài viết</a>
                            </div>
                        </div>
                        @include('admin.includes.success')
                        <div class="table-responsive">

                            <table id="postTable"
                                   class="table table-bordered table-striped table-hover js-basic-example dataTable"></table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
@stop

@section('javascript')
    <script>
        var postUrlJsonData = "{{route('admin.posts.as.json')}}";
        var postUrlPage = "{{route('posts.index')}}";
        var userUrlPage = "{{route('users.index')}}";
        var categoryUrlPage = "{{route('categories.index')}}";
    </script>
    <script src="/admin/js/pages/posts/index.js"></script>
@stop